### ISSUE TITLE
Add support for IR devices

### ISSUE THREAD

**Issue by DaronLord** [dustindclark/homebridge-globalcache-itach#1]
I am interested in using you plugin.  Do you have an example config.json file.  I currently don't see where I specify the IR Code for the itach module.  Thanks in advance.

**Comment by dustindclark** [comment]
@DaronLord, I just added a readme with a config example.  I'm currently only supporting contact closures, but I have an IR device on order that will be here Tuesday.  I should have IR support within a few days of receiving the device.

**Comment by DaronLord** [comment]
Thank you Dustin.  I have 3 of these devices and using Siri/HomeKit would be awesome.

Daron

**Comment by dustindclark** [comment]
@DaronLord , I've included IR support and added the example configuration to the readme.  This has also been published in 0.1.1.  There's also an option for enabling learn logging (point a remote at the back of the iTach and watch the codes being sent in the homebridge logs).  Give it a go and let me know if you have issues.

**Comment by DaronLord** [comment]
Hello Dustin,

Sorry for the delay in responding.  The plugin works great.  I have a quick question.  I was able to successfully set up one Itachi Device without issue.  When I try to setup a second device it fails.  How would I set up 3 separate devices with 3 ports.  Home bridge complains that you cannot setup multiple accessories with the same UUID.  Do I need to add an entry for each physical device under [platforms] or [devices] under the Itachi [devices] section.  I tried it both ways and it fails.  I will include the config.son in a separate post.

**Comment by DaronLord** [comment]
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:02",
        "pin": "987-65-432"
    },
    "platforms": [
        {
            "platform": "Nest",
            "username": "daron.lord@gmail.com",
                    "password": "XXXXXX"
        },
        {
                    "platform": "HarmonyHub",
                    "name": "Master Suite Hub",
            "ip_address": "192.168.1.91"
                },
        {
            "platform": "HarmonyHub",
            "name": "Gameroom Hub",
            "ip_address": "192.168.1.93"
        },
        {
            "platform": "GlobalCacheItach",
            "name": "IR Remote 1",
            "devices": [
                {
                    "name": "Kitchen Devices",
                    "host": "192.168.1.7",
                    "enableLearnLogging": false,
                    "ports": 
                    [
                        {
                            "name": "Kitchen TV",
                            "commands": {
                                "on": "1,38109,1,1,342,170,22,21,22,21,22,64,22,21,22,21,22,21,22,21,22,21,22,64,22,64,22,21,22,64,22,64,22,64,22,64,22,64,22,21,22,21,22,21,22,64,22,21,22,21,22,21,22,21,22,64,22,64,22,64,22,21,22,64,22,64,22,64,22,64,22,1517,342,85,22,3661,342,85,22,3810",
                                "off": "1,38109,1,1,342,170,22,21,22,21,22,64,22,21,22,21,22,21,22,21,22,21,22,64,22,64,22,21,22,64,22,64,22,64,22,64,22,64,22,21,22,21,22,21,22,64,22,21,22,21,22,21,22,21,22,64,22,64,22,64,22,21,22,64,22,64,22,64,22,64,22,1517,342,85,22,3661,342,85,22,3810"
                            }
                        }, {
                            "disable": true
                        }, {
                            "disable": true
                        }
                    ]
                },
                {
                    "name": "Room 2 Devices",
                    "host": "192.168.1.6",
                    "enableLearnLogging": false,
                    "ports": 
                    [
                        {
                            "name": "Room 2 TV",
                            "commands": {
                                "on": "1,39682,2,1,10,462,4,45,4,68,4,44,5,42,5,42,7,1040,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1023,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,3968",
                                "off": "1,39682,2,1,10,462,4,45,4,68,4,44,5,42,5,42,7,1040,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1023,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,1024,96,23,49,23,24,23,49,23,24,23,49,23,24,23,24,23,49,23,24,23,24,23,24,23,24,3968"
                            }
                        }, {
                            "disable": true
                        }, {
                            "disable": true
                        }
                    ]
                }

```
        ]
    }
]
```

}

**Comment by DaronLord** [comment]
Here is the exact error:

/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:175
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: f816f7e4-f665-4a31-97e7-b972412d8712
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:175:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:224:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at ItachPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:104:25)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-globalcache-itach/index.js:308:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by TangoEcho** [comment]
Did you ever find a solution for that?

**Comment by mrh335** [comment]
Are RS232 devices supported with this plugin or are there plans to support it?
