### ISSUE TITLE
Relay Codes

### ISSUE THREAD

**Issue by rpmartinez3** [dustindclark/homebridge-globalcache-itach#11]
Hi, I currently have a global cache relay that I use with Roomie Remote (Simple Control Remote) to open/close my garage door. I would like to get ride of Roomie remote and use this relay with Homebridge.. but how do I go about getting  the relay code to insert in the plugins programming?

**Comment by dustindclark** [comment]
Set enableLearnLogging to true in config, restart Homebridge, then point a remote at your itach device, press the combinations that you want to program, then capture from Homebridge logs.

**Comment by rpmartinez3** [comment]
> Set enableLearnLogging to true in config, restart Homebridge, then point a remote at your itach device, press the combinations that you want to program, then capture from Homebridge logs.

There isn't a remote. It's all controlled currently thru an app on an iphone. The global cache relay im using doesn't have IR.

Here's a link to it: [Flex Relay](https://www.globalcache.com/products/flex/flc-rsspec/)

**Comment by dustindclark** [comment]
oh gotcha. In that case, you don't need IR codes. Look at the non-IR config examples in the readme. I have not tested with your specific device, but it should work if itach hasn't changed things.

**Comment by rpmartinez3** [comment]
> oh gotcha. In that case, you don't need IR codes. Look at the non-IR config examples in the readme. I have not tested with your specific device, but it should work if itach hasn't changed things.

Ok thanks, I think I was over complicating it in my head.. so you're saying that I would only need to work with this section..![image](https://user-images.githubusercontent.com/22985495/140975432-2c9ed0a1-1e14-4e29-841a-6be4acf5f806.jpeg)

**Comment by dustindclark** [comment]
Correct. It's been a while since I've used this, but as far as I know, it still works on the latest versions...haven't seen any reported issues.

**Comment by rpmartinez3** [comment]
> Correct. It's been a while since I've used this, but as far as I know, it still works on the latest versions...haven't seen any reported issues.

Ok, would you be able to explain to me what both of the disable commands are doing?
