### ISSUE TITLE
ios10 

### ISSUE THREAD

**Issue by andrewdutoit1978** [dustindclark/homebridge-globalcache-itach#5]
Hi,

Module works with IOS 10 but as soon as I execute the 1st command none of my devices can update and become unavailalble in the homekit app.

I need to restart homebridge to get updates going again. On/off commands still seem to work even though everything is unavailable

Any ideas?

**Comment by dustindclark** [comment]
Closing this out since it's super old. May be able to revisit soon based on comments in #10. Reopen with details and logs if this is still an issue.
