### ISSUE TITLE
IR devices become unresponsive after a couple of activations

### ISSUE THREAD

**Issue by wildechild55** [dustindclark/homebridge-globalcache-itach#8]
The plugin works great! I have one issue If i activate a IR device, say the TV, then turn off the device, multiple times, (three to be exact) the device becomes unresponsive and won't let you interact with it. (I noticed this as I was excited trying out siri and my tv haha) any thoughts to what would be causing this? home bridge doesn't crash, I can still activate my other items Ex. hue lights, but not my tv.

**Comment by alexeyshulzhenko** [comment]
@wildechild55 i have the same issue and can't find where everything goes wrong. Connected air conditioner. After turning it on/off for a few times - this accessory become stoped working.

**Comment by dustindclark** [comment]
Closing this out since it's super old. May be able to revisit soon based on comments in #10. Reopen with details and logs if this is still an issue.
